### ISSUE TITLE
cant insert data

### ISSUE THREAD

**Issue by rallagas** [iam-chelle/Byte_Me#1]
registration.php

use 
include "inc/db_conn.php"

instead of coding the whole connection strings and parameters

**Comment by rallagas** [comment]
lines 12-20 is the connection part

always declare connections at the 1st line of the php file using include "db_conn.php"
or 
include_once "db_conn.php";

**Comment by JepKun** [comment]
okay na po sir yung issue sa registration namin . binalik ko lng po yung code na binigay nyo dun sa lab act 6 and nagdagdag ng konting code sa baba nun. thank you po sir sa tulong
update ko na po yung registration.php namin irename ko po sya as signup.php

**Comment by rallagas** [comment]
good job. dun sa kanban nyo imove nyo na sa completed
